### ISSUE TITLE
Seems like there is a lot of issues

### ISSUE THREAD

**Issue by benzon** [Profex1999/gridsystem#1]
First of all the fxmanifest is not compleat from start.

Missing client side script that is not in the sub folder.

Doubble enter registration, and exit seems to drop a error every single time, it seems like it's not to happy getting 2 events just after each other got 2 events named 2 different things and it registers the same name for both of them not sure why.

**Comment by benzon** [comment]
the idea is great, think it needs to be error fixed abit tho.

**Comment by Profex1999** [comment]
Thanks for your feedback. Unfortunately I can't reproduce the problems you described. What is missing client side, to me it seems every file is loaded. I tested  by registering 10 markers in a for loop with not Wait at all and everything was working fine.

> Doubble enter registration, and exit seems to drop a error every single time, 

Can you send screen of the errors?
Thank you

**Comment by benzon** [comment]
Your fxmanifest got do be different very very different
![162125909618fbb0f0520ff406f4425840710cf1f0](https://user-images.githubusercontent.com/3528000/118499024-dbd8f080-b726-11eb-8b5d-a104f9127b0d.jpg)

Only files loaded in this manifest is classes/marker.lua

Missing files events.lua, functions.lua, grid.lua, main.lua

Ill post the rest of the issues later, it's not to be a dick, just trying to help out :)

**Comment by Profex1999** [comment]
Don't worry, I appreciate feedbacks!
For the fxmanifest maybe you are using an old version of fx server because on my side everything is loaded correctly. In other languages `**/*.lua*`  means "find any files ending with .lua extension in the current folder and recursively in any sub folder". If it's not loading all the files on your side that's very weird,  I don't get why it works normally on my PC and not in yours/others.

**Comment by benzon** [comment]
Stil not able to get it to work like intended.

**Comment by Profex1999** [comment]
I dont' know what to say. I just tested with a fresh esx server (the PlumeESX template from txadmin), put this resource in and tried to register a marker. Everything was working just fine (both with and without the job) so without any screenshot of errors/more info I can't know what is causing your issues.

**Comment by benzon** [comment]
So found first issue now.

The example code is messed up :D

So the event is spelled wrong, and there is a missing , that i noticed some time ago the missing ,

You are right the files load correct, ill test it again, right now it looks like it works as intended, just gonna test with a diffent test setup.

```
TriggerEvent('gridsystem:registerMarker', {
    name = 'this is it',
    pos = vector3(219.17007446289,-809.17559814453,30.686813354492),
    scale = vector3(1.5, 1.5, 1.5),
    msg = 'Press ~INPUT_CONTEXT~ to do something',
    control = 'E',
    type = 20,
    color = {r = 130, g = 120, b = 110},
    action = function()
        print('This is executed when you press E in the marker')
    end,
    onEnter = function()
        print('This is executed when you enter a marker')
    end,
    onExit = function()
        print('This is executed when you eixit a marker')
    end
})
```

**Comment by benzon** [comment]
Okay so that works.

So forceExit causes an error.
![1622026659833a8e5cb213c7d0649dff8eaac4472b](https://user-images.githubusercontent.com/3528000/119648742-1b3bc700-be22-11eb-8b4c-f8c0eb8fe224.jpg)

Would wish there where a function to renable the prompt again after a menu is shutdown, so it only causes a temp exit while in menus.

**Comment by Profex1999** [comment]
Ohh didn't notice D: . Now the README should be correct.
I also fixed the forceExit error. Now ,if set to true, after pressing a control in a marker you must exit and enter again to be able to press the control key again.

**Comment by benzon** [comment]
Okay super, hmm would it be possible to do a feature so you can pause it somehow - i know it's a long stretch, so if you open a menu it deactivates until the menu is closed, or might that be a to big issue?

**Comment by Profex1999** [comment]
> Okay super, hmm would it be possible to do a feature so you can pause it somehow - i know it's a long stretch, so if you open a menu it deactivates until the menu is closed, or might that be a to big issue?

Mmmm I'm sure i understand what you mean. Like you press the key, it opens a menu and then it utomatically close when you exit?

**Comment by Profex1999** [comment]
Sorry for the late response but i had other things to do in these days

**Comment by benzon** [comment]
No so ex. if you open a menu, it stops showing help tekst, and stop drawing the marker, when you exit the menu tho, it redraws and shows the help text, so you dont have to go in and out of the marker.

**Comment by Profex1999** [comment]
> No so ex. if you open a menu, it stops showing help tekst, and stop drawing the marker, when you exit the menu tho, it redraws and shows the help text, so you dont have to go in and out of the marker.

Yes I can do it. I'll work on it in the next days

**Comment by benzon** [comment]
On force exit i do think the draw should stop until marker is left to - since there is no reason for the marker or 3D text to keep showing after.

Besides that, a thing that would make alot of sence, using it for ex. ped's to, so build in function where you define if it's a marker or a ped that should be spawned, would make a lot of sence.

**Comment by benzon** [comment]
Got a concern on the registry of markers, if you got markers where you put in a job, they need to have a wait timer else they will get the same Z value and it will mess up totaly, if you got a wait of 100 ms it will work like intended, my thought here tho, if you then got multiple job scripts sending in coords at the same time, it would prob mess up again.

A server side solution might be the best here, where you actually send it to the server, and the server forwards it to the client so it get's added with a slow pace - so it dos not mess up.
