### ISSUE TITLE
Optimizing grid with a quad-tree implementation. 

### ISSUE THREAD

**Issue by Profex1999** [Profex1999/gridsystem#3]
I think it would be faster performance-wise, to implement a quad-tree data structure instead of relying on the grid. Something like this
https://observablehq.com/@d3/quadtree-findincircle

**Comment by benzon** [comment]
Noticed this on CFX Forums today, might be something you wanna look in to.
https://github.com/negbook/quadtree

**Comment by Profex1999** [comment]
Interesting, i will take a look at that!

**Comment by Profex1999** [comment]
In the end the current implementation already suffice for the majority of cases.
